version: '3.8'

services:
  mongo:
    image: mongo:5
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

##### docker comandos #####

#0) listar imagenes: docker ps

#1) ingresar a contenedor: docker exec -it mongodb bash

#2) copiar archivos en contenedor docker: cp -a ./dump_bson mongodb:/dump

#3) correr restaurar base de datos con dump: docker exec -i mongodb /usr/bin/mongorestore --username root --password example --authenticationDatabase admin --db ucropitqa /dump/dump_bson